In [1]:
import pandas as pd

In [2]:
books = pd.read_csv('books_cleaned_new.csv')

In [ ]:
books['categories'].value_counts().reset_index().query('count >= 18')

                     categories  count
0                       Fiction   2111
1              Juvenile Fiction    390
2     Biography & Autobiography    311
3                       History    207
4            Literary Criticism    124
5                    Philosophy    117
6                      Religion    117
7       Comics & Graphic Novels    116
8                         Drama     86
9           Juvenile Nonfiction     57
10                      Science     56
11                       Poetry     51
12         Literary Collections     50
13         Business & Economics     49
14               Social Science     48
15              Performing Arts     40
16                      Cooking     35
17                   Psychology     33
18                       Travel     32
19                          Art     32
20          Body, Mind & Spirit     32
21            Political Science     30
22             Health & Fitness     28
23                    Self-Help     28
24                    Computers     28
25       Family & Relationships     27
26  Language Arts & Disciplines     23
27                        Humor     23
28                      Medical     19
29                       Nature     19
30           Children's stories     18

In [16]:
books[books['categories']=="Children's stories"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_&_subtitle,tagged_description
939,9.780193e+12,0192752537,Party Shoes,Noel Streatfeild,Children's stories,http://books.google.com/books/content?id=aYCk-...,"Near the end of the Second World War, Selina r...",2002.0,3.64,243.0,417.0,Party Shoes,9780192752536.0 Near the end of the Second Wor...
1075,9.780238e+12,0237526883,"20,000 Leagues Under the Sea",Jules Verne;Pauline Francis,Children's stories,http://books.google.com/books/content?id=qnNyp...,The abridged adventures of a French professor ...,2004.0,3.76,48.0,543.0,"20,000 Leagues Under the Sea",9780237526887.0 The abridged adventures of a F...
1430,9.780341e+12,0340796154,Five Go Adventuring Again,Enid Blyton,Children's stories,http://books.google.com/books/content?id=sAB4N...,"The Famous Five--Julian, Dick, Anne, George, a...",2001.0,4.01,246.0,11757.0,Five Go Adventuring Again,"9780340796153.0 The Famous Five--Julian, Dick,..."
2160,9.780440e+12,0439944392,Hello! Is That Grandma?,Ian Whybrow;Deborah Allwright,Children's stories,http://books.google.com/books/content?id=cepoN...,Who's on the phone? Lift the flaps and see! Im...,2007.0,3.51,32.0,54.0,Hello! Is That Grandma?,9780439944397.0 Who's on the phone? Lift the f...
2634,9.780553e+12,0552548227,Spindle's End,Robin McKinley,Children's stories,http://books.google.com/books/content?id=W6Ev8...,"""The princess has been missing since she was a...",2003.0,3.80,464.0,184.0,Spindle's End,"9780552548229.0 ""The princess has been missing..."
2636,9.780553e+12,0552554278,Vox,Paul Stewart;Chris Riddell,Children's stories,http://books.google.com/books/content?id=FcCBW...,"""High in the crumbling Palace of Statues, oily...",2006.0,4.11,400.0,54.0,Vox,"9780552554275.0 ""High in the crumbling Palace ..."
2963,9.780671e+12,0670913529,Artemis Fowl,Eoin Colfer,Children's stories,http://books.google.com/books/content?id=TOqeP...,"Twelve-year-old villain, Artemis Fowl, is the ...",2003.0,4.05,329.0,179.0,Artemis Fowl:The Eternity Code,"9780670913527.0 Twelve-year-old villain, Artem..."
3397,9.780743e+12,0743461517,"Click, Clack, Moo",Doreen Cronin;Betsy Lewin,Children's stories,http://books.google.com/books/content?id=VtszA...,Farmer Brown has a problem. His cows like to t...,2003.0,4.24,30.0,337.0,"Click, Clack, Moo:Cows that Type",9780743461511.0 Farmer Brown has a problem. Hi...
3471,9.780748e+12,0747566828,"Super Fast, Out of Control!",Louis Sachar,Children's stories,http://books.google.com/books/content?id=cFubP...,The seventh story in the series featuring all ...,2005.0,3.75,128.0,0.0,"Super Fast, Out of Control!",9780747566823.0 The seventh story in the serie...
3472,9.780748e+12,0747569118,Wayside School Gets a Little Stranger,Louis Sachar,Children's stories,http://books.google.com/books/content?id=vUs-P...,All the kids at Wayside had to spend 243 days ...,2004.0,4.19,176.0,17456.0,Wayside School Gets a Little Stranger,9780747569114.0 All the kids at Wayside had to...
3483,9.780750e+12,0749858524,Little Miss Scary,Adam Hargreaves;Roger Hargreaves,Children's stories,http://books.google.com/books/content?id=8mFYA...,Little Miss Bad is not good. She is always doi...,2003.0,3.73,32.0,175.0,Little Miss Scary,9780749858520.0 Little Miss Bad is not good. S...
3484,9.780750e+12,0749858532,Little Miss Bad,Roger Hargreaves,Children's stories,http://books.google.com/books/content?id=4IgNA...,Little Miss Bad is not good. Far from it. In f...,2003.0,3.89,34.0,224.0,Little Miss Bad,9780749858537.0 Little Miss Bad is not good. F...
3507,9.780752e+12,0752224417,The Lost World,Gail Herman,Children's stories,http://books.google.com/books/content?id=YXhuP...,Summer 1997 will see the release of Steven Spi...,1997.0,3.76,448.0,95109.0,The Lost World:Jurassic Park : the Junior Nove...,9780752224411.0 Summer 1997 will see the relea...
4457,9.781405e+12,1405203951,The Mystery of the Secret Room,Enid Blyton,Children's stories,http://books.google.com/books/content?id=msjbA...,A fantastic children’s crime story from the wo...,2009.0,4.04,217.0,2258.0,The Mystery of the Secret Room,9781405203951.0 A fantastic children’s crime s...
5016,9.781845e+12,1845390105,Scary Edwin Page,Alec Sillifant;Daniel Postgate,Children's stories,http://books.google.com/books/content?id=uikcO...,Edwin Page was scarier than a bin bag full of ...,2004.0,3.21,24.0,14.0,Scary Edwin Page,9781845390105.0 Edwin Page was scarier than a ...
5123,9.781903e+12,1903015073,The Spiral Stair,Joan Aiken;Quentin Blake,Children's stories,http://books.google.com/books/content?id=y2plA...,With Noah the boa using his coils to work the ...,2000.0,4.38,62.0,33.0,The Spiral Stair,9781903015070.0 With Noah the boa using his co...
5124,9.781903e+12,1903252040,The Elephant War,Gillian Avery,Children's stories,http://books.google.com/books/content?id=kvX7A...,"Based on a true incident in 1882, this gentle ...",2000.0,3.68,256.0,17.0,The Elephant War,9781903252048.0 Based on a true incident in 18...
5126,9.781904e+12,1904233198,To the Blight,Robert Jordan,Children's stories,http://books.google.com/books/content?id=bURfP...,Despite the magical aid of Moraine Sedai and t...,2003.0,4.23,500.0,1101.0,To the Blight,9781904233190.0 Despite the magical aid of Mor...

In [17]:
category_mapping = {
    'Fiction': "Fiction",
    'Juvenile Fiction': "Fiction",
    'Biography & Autobiography': "Nonfiction",
    'History': "Nonfiction",
    'Literary Criticism': "Nonfiction",
    'Philosophy': "Nonfiction",
    'Religion': "Nonfiction",
    'Comics & Graphic Novels': "Fiction",
    'Drama': "Fiction",
    'Juvenile Nonfiction': "Nonfiction",
    'Science': "Nonfiction",
    'Poetry': "Fiction",
    'Literary Collections': "Nonfiction",
    'Business & Economics': "Nonfiction",
    'Social Science': "Nonfiction",
    'Performing Arts': "Nonfiction",
    'Cooking': "Nonfiction",
    'Psychology': "Nonfiction",
    'Travel': "Nonfiction",
    'Art': "Nonfiction",
    'Body, Mind & Spirit': "Nonfiction",
    'Political Science': "Nonfiction",
    'Health & Fitness': "Nonfiction",
    'Self-Help': "Nonfiction",
    'Computers': "Nonfiction",
    'Family & Relationships': "Nonfiction",
    'Language Arts & Disciplines': "Nonfiction",
    'Humor': "Fiction",
    'Medical': "Nonfiction",
    'Nature': "Nonfiction",
    "Children's stories": "Fiction"
}

books["simple_categories"] = books["categories"].map(category_mapping)

In [22]:
books[:1]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_&_subtitle,tagged_description,simple_categories
0,9.780002e+12,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883.0 A NOVEL THAT READERS and criti...,Fiction

In [29]:
len(books[(books['simple_categories'].isna())]), len(books[~(books['simple_categories'].isna())])

(860, 4337)

In [36]:
from transformers import pipeline

In [37]:
fiction_categories = ["Fiction", "Nonfiction"]

In [40]:
pipe = pipeline("zero-shot-classification",
                model="cross-encoder/nli-distilroberta-base",
                device="cpu")

Device set to use cpu

In [44]:
sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[3]

In [45]:
result = pipe(sequence, fiction_categories)

In [47]:
import numpy as np

In [52]:
max_index = np.argmax(pipe(sequence, fiction_categories)['scores'])
max_label = pipe(sequence, fiction_categories)['labels'][max_index]
max_label

'Fiction'

In [53]:
def generate_predictions(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(pipe(sequence, fiction_categories)['scores'])
    max_label = pipe(sequence, fiction_categories)['labels'][max_index]
    return max_label

In [54]:
from tqdm import tqdm

In [55]:
actual_cats = []
predicted_cats = []
for i in tqdm(range(0,300)):
    sequence = books.loc[books['simple_categories']=='Fiction', 'description'].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ['Fiction']

100%|██████████| 300/300 [01:13<00:00,  4.08it/s]

In [56]:
for i in tqdm(range(0,300)):
    sequence = books.loc[books['simple_categories']=='Nonfiction', 'description'].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ['Nonfiction']

100%|██████████| 300/300 [01:17<00:00,  3.85it/s]

In [57]:
predictions_df = pd.DataFrame({"actual_cats": actual_cats, "predicted_cats": predicted_cats})
predictions_df

    actual_cats predicted_cats
0       Fiction     Nonfiction
1       Fiction        Fiction
2       Fiction        Fiction
3       Fiction        Fiction
4       Fiction        Fiction
..          ...            ...
595  Nonfiction        Fiction
596  Nonfiction        Fiction
597  Nonfiction        Fiction
598  Nonfiction     Nonfiction
599  Nonfiction        Fiction

[600 rows x 2 columns]

In [59]:
predictions_df["correct_preds"] = (
    np.where(predictions_df["actual_cats"] == predictions_df['predicted_cats'], 1, 0)
)
predictions_df['correct_preds'].sum()/len(predictions_df)

np.float64(0.5616666666666666)

In [60]:
isbns = []
predicted_cats = []

missing_cats = books.loc[books["simple_categories"].isna(), ["isbn13", "description"]].reset_index(drop=True)

In [61]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    isbns += [missing_cats["isbn13"][i]]

100%|██████████| 860/860 [03:23<00:00,  4.23it/s]

In [62]:
missing_predicted_df = pd.DataFrame({"isbn13": isbns, "predicted_categories": predicted_cats})

In [63]:
missing_predicted_df.head()

         isbn13 predicted_categories
0  9.780002e+12              Fiction
1  9.780006e+12              Fiction
2  9.780006e+12              Fiction
3  9.780006e+12              Fiction
4  9.780006e+12              Fiction

In [64]:
books = pd.merge(books, missing_predicted_df, on="isbn13", how="left")
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_categories"], books["simple_categories"])
books = books.drop(columns = ["predicted_categories"])

In [65]:
books.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_&_subtitle,tagged_description,simple_categories
0,9.780002e+12,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883.0 A NOVEL THAT READERS and criti...,Fiction
1,9.780002e+12,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web:A Novel,9780002261982.0 A new 'Christie for Christmas'...,Fiction
2,9.780006e+12,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736.0 A memorable, mesmerizing heroi...",Fiction
3,9.780006e+12,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897.0 Lewis' work on the nature of l...,Fiction
4,9.780006e+12,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934.0 ""In The Problem of Pain, C.S. ...",Fiction

In [68]:
books.isnull().sum()

isbn13                  0
isbn10                  0
title                   0
authors                32
categories             30
thumbnail             166
description             0
published_year          0
average_rating          0
num_pages               0
ratings_count           0
title_&_subtitle        0
tagged_description      0
simple_categories       0
dtype: int64

In [69]:

books.to_csv("books_with_cats.csv", index=False)